script:
  - cd backend
  - mvn clean install -Pdev
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UnimibSoftEngCourse2021_progetto-birra-2-gruppo-birra-2
  - docker build -t gruppobirra2/brewday:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gruppobirra2/brewday:latest
  - ${DEV-EC2-KEY} > dev.pem
  - chmod 600 dev.pem
  - ssh -oStrictHostKeyChecking=accept-new -i dev.pem ${DEV-EC2-USERNAME}@${DEV-EC2-URL} touch test.txt

addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token: ${SONAR_TOKEN}

services:
  - docker

language: java
jdk:
    - openjdk11