language: java
jdk:
    - openjdk11

addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token: ${SONAR_TOKEN}
  ssh_known_hosts: ${DEV_EC2_URL}

services:
  - docker

branches:
  only:
  - main
  - Develop

script:
  - cd backend
  - mvn clean install -Pdev
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UnimibSoftEngCourse2021_progetto-birra-2-gruppo-birra-2 -DskipTests=true; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then docker build -t gruppobirra2/brewday:latest .; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then docker push gruppobirra2/brewday:latest; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd ..; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd maximizebrewtoday; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then docker build -t gruppobirra2/maximizebrewtoday:latest .; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then docker push gruppobirra2/maximizebrewtoday:latest; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd ..; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd frontend; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then docker build -t gruppobirra2/brewday-frontend:latest .; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then docker push gruppobirra2/brewday-frontend:latest; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd ..; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd script; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then chmod +x deploy.sh; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "${DEV_EC2_KEY}" > dev.pem; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then chmod 600 dev.pem; fi



deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -o "StrictHostKeyChecking no" -i dev.pem ${DEV_EC2_USERNAME}@${DEV_EC2_URL} "bash -s" < ./deploy.sh
    on:
      branch: Develop