script:
  - cd backend
  - mvn clean install -Pdev
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=UnimibSoftEngCourse2021_progetto-birra-2-gruppo-birra-2

addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token: ${SONAR_TOKEN}

language: java
jdk:
    - openjdk11