script:
  - cd backend
  - mvn clean install -Pdev
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UnimibSoftEngCourse2021_progetto-birra-2-gruppo-birra-2 -DskipTests=true
  - docker build -t gruppobirra2/brewday:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gruppobirra2/brewday:latest
  - echo "${DEV_EC2_KEY}" > dev.pem
  - chmod 600 dev.pem
  - ssh -o "StrictHostKeyChecking no" -i dev.pem ${DEV_EC2_USERNAME}@${DEV_EC2_URL} touch test.txt

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - ssh -o "StrictHostKeyChecking no" -i dev.pem ${DEV_EC2_USERNAME}@${DEV_EC2_URL} touch deploy.txt
    on:
      branch: develop

addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token: ${SONAR_TOKEN}
  ssh_known_hosts: ${DEV_EC2_URL}

services:
  - docker

language: java
jdk:
    - openjdk11