apiVersion: v1
kind: Service
metadata:
  name: maximizebrewtoday
  namespace: brewday
  labels:
    run: maximizebrewtoday
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: maximizebrewtoday
  type: LoadBalancer