apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: brewday
  name: brewday
  namespace: brewday
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brewday
  strategy: {}
  template:
    metadata:
      labels:
        app: brewday
    spec:
      containers:
      - image: gruppobirra2/brewday:prod
        imagePullPolicy: "Always"
        name: brewday
        ports:
            - containerPort: 8080