apiVersion: v1
kind: Service
metadata:
  name: brewday
  namespace: brewday
  labels:
    run: brewday
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: brewday
  type: LoadBalancer