apiVersion: v1
kind: Service
metadata:
  name: brewday-frontend
  namespace: brewday
  labels:
    run: brewday-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: brewday-frontend
  type: LoadBalancer