spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/progetto-is?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Rome
    username: root
    password: progetto-is

MaximizeBrewService:
  ribbon:
    listOfServers : http://localhost:5000




