spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

  profiles:
        active: "@profileActive@"

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/progetto-is?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Rome
    username: root
    password: progetto-is




