# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: 
    - main
    - develop
  pull_request:
    branches: 
    - main
    - develop

env:
  SONAR_TOKEN: 42990b8f57387714ba3e1d30f3b4d3d374fa5f54
  GITHUB_TOKEN: d4d0ea24d166f0f5ae4124a6692ea7afca6db150
  DOCKER_HUB_USERNAME: gruppobirra2
  DOCKER_HUB_ACCESS_TOKEN: 85835093-a510-4f6d-8667-d91134f69860     

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        cd backend
        mvn clean install -DskipTests=true
        
    -

        name: Login to DockerHub

        uses: docker/login-action@v1 

        with:

          username: gruppobirra2

          password: 85835093-a510-4f6d-8667-d91134f69860
    -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

    -

        name: Build and push

        id: docker_build_backend

        uses: docker/build-push-action@v2

        with:
          context: ./backend 

          file: ./backend/Dockerfile

          push: true

          tags: gruppobirra2/brewday:dev
    -

        name: Build and push

        id: docker_build_frontend

        uses: docker/build-push-action@v2

        with:
          context: ./frontend 

          file: ./frontend/Dockerfile

          push: true

          tags: gruppobirra2/brewday-frontend:dev
    -

        name: Build and push

        id: docker_build_maximizebrew

        uses: docker/build-push-action@v2

        with:
          context: ./maximizebrewtoday 

          file: ./maximizebrewtoday/Dockerfile

          push: true

          tags: gruppobirra2/maximizebrewtoday:dev
